# data load

In [1]:
import os
import pandas as pd
from tqdm import tqdm
from pshmodule.utils import filemanager as fm
import config

In [3]:
file_list = []
data_path = config.data_dir_path
dir_path = data_path
for (root, directories, files) in os.walk(dir_path):
    for file in files:
        file_path = os.path.join(root, file)
        file_list.append(file_path.replace(data_path, ''))

In [4]:
file_list

['1999.xlsx',
 '2000.xlsx',
 '2001.xlsx',
 '2002.xlsx',
 '2003.xlsx',
 '2004.xlsx',
 '2005.xlsx',
 '2006.xlsx',
 '2007.xlsx',
 '2008.xlsx',
 '2009.xlsx',
 '2010.xlsx',
 '2011.xlsx',
 '2012.xlsx',
 '2013.xlsx',
 '2014.xlsx',
 '2015.xlsx',
 '2016.xlsx',
 '2017.xlsx',
 '2018.xlsx',
 '2019.xlsx',
 '2020.xlsx',
 '2021.xlsx']

In [5]:
for k, v in tqdm(enumerate(file_list)):
    vv = v.replace(".xlsx", "")
    globals()[f"df_{vv}"] = pd.read_excel(data_path + str(v), sheet_name="사업과제정보")

0it [00:00, ?it/s]/opt/conda/lib/python3.8/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
23it [30:23, 79.27s/it]

In [6]:
df_1999.head()

,제출년도,사업명,사업구분,사업_부처명,계속과제여부구분코드,계속과제여부,이전(기관)세부과제번호,이전과제고유번호,내역사업명,(기관)세부과제번호,...,참여연구원_전공_공학,참여연구원_전공_농학,참여연구원_전공_의학,참여연구원_전공_인문,참여연구원_전공_기타,연구책임자소속기관명,연구책임자사업자번호,연구책임자성별,연구책임자전공,연구책임자학위
0,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4719,...,NaN,NaN,NaN,NaN,NaN,NaN,*******00*,NaN,NaN,NaN
1,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4725,...,NaN,NaN,NaN,NaN,NaN,NaN,*******00*,NaN,NaN,NaN
2,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4673,...,NaN,NaN,NaN,NaN,NaN,NaN,*******00*,NaN,NaN,NaN
3,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4726,...,NaN,NaN,NaN,NaN,NaN,NaN,*******00*,NaN,NaN,NaN
4,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4734,...,NaN,NaN,NaN,NaN,NaN,NaN,*******00*,NaN,NaN,NaN

In [7]:
df_2021.head()

,제출년도,사업명,사업구분,사업_부처명,계속과제여부구분코드,계속과제여부,이전(기관)세부과제번호,이전과제고유번호,내역사업명,(기관)세부과제번호,...,참여연구원_전공_공학,참여연구원_전공_농학,참여연구원_전공_의학,참여연구원_전공_인문,참여연구원_전공_기타,연구책임자소속기관명,연구책임자사업자번호,연구책임자성별,연구책임자전공,연구책임자학위
0,2021,정책연구개발사업(R&D),인문사회연구개발사업,교육부,1,신규,NaN,NaN,정책연구개발사업-28,정책연구개발사업-28,...,0,0,0,0,0,대전대학,*******38*,NaN,NaN,NaN
1,2021,정책연구개발사업(R&D),인문사회연구개발사업,교육부,1,신규,NaN,NaN,정책연구개발사업-27,정책연구개발사업-27,...,0,0,0,0,0,한국직업능력연구원,*******55*,NaN,NaN,NaN
2,2021,정책연구개발사업(R&D),인문사회연구개발사업,교육부,1,신규,NaN,NaN,정책연구개발사업-26,정책연구개발사업-26,...,0,0,0,0,0,성신여자대학,*******39*,NaN,NaN,NaN
3,2021,정책연구개발사업(R&D),인문사회연구개발사업,교육부,1,신규,NaN,NaN,정책연구개발사업-25,정책연구개발사업-25,...,0,0,0,0,0,전남대학교산학협력단,*******94*,NaN,NaN,NaN
4,2021,정책연구개발사업(R&D),인문사회연구개발사업,교육부,1,신규,NaN,NaN,정책연구개발사업-24,정책연구개발사업-24,...,0,0,0,0,0,조선대학,*******41*,NaN,NaN,NaN

In [8]:
df_name = ["df_" + i.replace('.xlsx', '') for i in file_list]
print(df_name)

['df_1999', 'df_2000', 'df_2001', 'df_2002', 'df_2003', 'df_2004', 'df_2005', 'df_2006', 'df_2007', 'df_2008', 'df_2009', 'df_2010', 'df_2011', 'df_2012', 'df_2013', 'df_2014', 'df_2015', 'df_2016', 'df_2017', 'df_2018', 'df_2019', 'df_2020', 'df_2021']

# processing

In [9]:
df = pd.concat([df_1999, df_2000, df_2001, df_2002, df_2003, df_2004, df_2005, df_2006, df_2007, df_2008, df_2009, df_2010, df_2011, df_2012, df_2013, df_2014, df_2015, df_2016, df_2017, df_2018, df_2019, df_2020, df_2021])

In [10]:
df.head()

,제출년도,사업명,사업구분,사업_부처명,계속과제여부구분코드,계속과제여부,이전(기관)세부과제번호,이전과제고유번호,내역사업명,(기관)세부과제번호,...,중점과학기술분류코드-대,중점과학기술분류-대,중점과학기술분류코드-중,중점과학기술분류-중,중점과학기술분류코드-소,중점과학기술분류-소,경제사회목적코드,경제사회목적,세부과제지원코드,세부과제지원유형
0,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4719,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4725,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4673,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4726,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1999,농업기술공동연구,NaN,농촌진흥청,NaN,NaN,NaN,NaN,NaN,1999-4734,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df = df[['제출년도', '과제수행기관명', '사업명', '내역사업명', '과제명', '요약문_연구내용', '세부과제지원유형', '과제고유번호']]

In [12]:
df.head()

,제출년도,과제수행기관명,사업명,내역사업명,과제명,요약문_연구내용,세부과제지원유형,과제고유번호
0,1999,NaN,농업기술공동연구,NaN,유전자조작에 의한 고Caroten oid 함량 고추분자육종소재개발,NaN,NaN,1395009431
1,1999,NaN,농업기술공동연구,NaN,환경보전형 농업을 위한 식물생장 촉진 미생물 개발,NaN,NaN,1395009432
2,1999,NaN,농업기술공동연구,NaN,농촌 현장 공동기술 개발,NaN,NaN,1395009260
3,1999,NaN,농업기술공동연구,NaN,환경친화형 정밀농업 기술 개발 연구,NaN,NaN,1395009384
4,1999,NaN,농업기술공동연구,NaN,농업용 신소재 및 실용화 기술 개발,NaN,NaN,1395009284

# data save

##### all df

In [13]:
fm.save(config.df_all_path, df)

Saved 990565 records